package com.mdkproject.mdkshiro.dao;

import com.mdkproject.mdkshiro.entity.SysUserRole;
import com.mdkproject.mdkshiro.entity.SysUserRoleExample;
import com.mdkproject.mdkshiro.entity.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jun 26 15:42:03 CST 2019
     */
    long countByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jun 26 15:42:03 CST 2019
     */
    int deleteByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jun 26 15:42:03 CST 2019
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jun 26 15:42:03 CST 2019
     */
    int insertSelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jun 26 15:42:03 CST 2019
     */
    List<SysUserRole> selectByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jun 26 15:42:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysUserRole record, @Param("example") SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jun 26 15:42:03 CST 2019
     */
    int updateByExample(@Param("record") SysUserRole record, @Param("example") SysUserRoleExample example);

    List<SysUserRole> selectByUid(Integer uid);

    //删除
    void deleteByUid(Integer uid);

    //删除角色时，删除对应的用户角色关系
    void deleteByRoleId(Integer roleId);

    //清除给用户分配的角色
    void deleteByUidAndRoleId(String uid, String roleId);


}